# Generated by Django 4.1.7 on 2023-09-09 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_image_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='security_answer_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='security_answer_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
