# Generated by Django 4.1.7 on 2023-09-10 11:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_date_adolescent_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adolescent',
            name='adolescent_type',
        ),
        migrations.RemoveField(
            model_name='adolescent',
            name='community',
        ),
        migrations.RemoveField(
            model_name='adolescent',
            name='school',
        ),
        migrations.AddField(
            model_name='adolescent',
            name='type',
            field=models.CharField(choices=[('primary', 'primary'), ('secondary', 'secondary'), ('community', 'community')], default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adolescent',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 9, 10, 11, 47, 35, 590441, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adolescent',
            name='check_up_location',
            field=models.CharField(max_length=200),
        ),
    ]
