# Generated by Django 4.1.7 on 2023-09-10 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_adolescent_adolescent_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adolescent',
            name='dob',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
