# Generated by Django 4.1.7 on 2023-12-04 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(db_index=True, max_length=120, primary_key=True, serialize=False),
        ),
    ]
