# Generated by Django 4.1.7 on 2023-09-10 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_adolescent_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adolescent',
            name='pid',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
