# Generated by Django 4.1.7 on 2024-03-18 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_user_gender_alter_user_other_names_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='content_hash',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
