# Generated by Django 4.1.7 on 2024-03-18 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_user_content_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='content_hash',
            field=models.TextField(blank=True, null=True),
        ),
    ]
