# Generated by Django 4.1.7 on 2024-03-18 14:17

from django.db import migrations, models
import ycheck.utils.storage


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_user_content_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, storage=ycheck.utils.storage.OverwriteStorage(), upload_to='users'),
        ),
    ]
