# Generated by Django 4.1.7 on 2024-03-19 16:19

import dashboard.models.mixin
import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0023_alter_user_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncGroup',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(dashboard.models.mixin.UpstreamSyncMethodsModel, 'auth.group'),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.CreateModel(
            name='SyncPermission',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(dashboard.models.mixin.UpstreamSyncMethodsModel, 'auth.permission'),
            managers=[
                ('objects', django.contrib.auth.models.PermissionManager()),
            ],
        ),
    ]
