# Generated by Django 5.0.4 on 2024-08-10 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_syncgroup_syncpermission'),
        ('dashboard', '0099_computedaverageactivitytime_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='dashboard.facility'),
        ),
    ]
