# Generated by Django 4.2.3 on 2023-09-06 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_homequestion_category_userresponse"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homequestion",
            name="options",
        ),
        migrations.AddField(
            model_name="homequestion",
            name="cation",
            field=models.CharField(default="none", max_length=200),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Option",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("option_id", models.CharField(max_length=255)),
                ("option", models.CharField(max_length=255)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.homequestion",
                    ),
                ),
            ],
        ),
    ]
