# Generated by Django 4.2.3 on 2023-09-06 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_remove_homequestion_options_homequestion_cation_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="HomeQuestion",
            new_name="Question",
        ),
    ]
