# Generated by Django 4.1.7 on 2023-09-20 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adolescent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, null=True)),
                ('pid', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('surname', models.CharField(max_length=50)),
                ('other_names', models.CharField(max_length=50)),
                ('visit_type', models.CharField(blank=True, max_length=50, null=True)),
                ('consent', models.CharField(blank=True, max_length=50, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('dob', models.DateTimeField(blank=True, null=True)),
                ('check_up_location', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('primary', 'primary'), ('secondary', 'secondary'), ('community', 'community')], max_length=20)),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('questionnaire_completed', models.BooleanField(default=False)),
                ('completed_question', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adolescent_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CheckupLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, null=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('type', models.CharField(choices=[('primary', 'primary'), ('secondary', 'secondary'), ('community', 'community')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('instruction', models.TextField()),
                ('question_type', models.CharField(choices=[('survey', 'survey'), ('assessment', 'assessment'), ('survey_feedback', 'survey_feedback')], default='survey', max_length=100)),
                ('number', models.IntegerField(unique=True)),
                ('requires_game', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SummaryFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admins_comment', models.TextField(blank=True, null=True)),
                ('caption', models.CharField(blank=True, default='', max_length=100)),
                ('question_type', models.TextField(choices=[('survey', 'survey'), ('assessment', 'assessment'), ('survey_feedback', 'survey_feedback')])),
                ('question_id', models.CharField(max_length=50, unique=True)),
                ('number', models.IntegerField(unique=True)),
                ('text', models.CharField(max_length=200)),
                ('input_type', models.CharField(choices=[('text_field', 'text_field'), ('number_field', 'number_field'), ('radio_button', 'radio_button'), ('checkboxes', 'checkboxes'), ('range_slider', 'range_slider')], max_length=100)),
                ('answer_preamble', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('min_numeric_value', models.IntegerField(blank=True, null=True)),
                ('max_numeric_value', models.IntegerField(blank=True, null=True)),
                ('type_of_visit', models.CharField(blank=True, max_length=100, null=True)),
                ('min_age', models.IntegerField(blank=True, null=True)),
                ('max_age', models.IntegerField(blank=True, null=True)),
                ('gender', models.IntegerField(blank=True, null=True)),
                ('adolescent_type', models.CharField(blank=True, choices=[('primary', 'primary'), ('secondary', 'secondary'), ('community', 'community')], max_length=100, null=True)),
                ('invert_adolescent_attribute_requirements', models.BooleanField(blank=True, default=False, null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='dashboard.section')),
            ],
        ),
        migrations.CreateModel(
            name='PreviousResponseRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_is', models.CharField(blank=True, max_length=100, null=True)),
                ('min_integer_value', models.IntegerField(blank=True, null=True)),
                ('is_inverted', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.question')),
                ('requirement_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previous_response_requirements', to='dashboard.question')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('numeric_value', models.IntegerField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='dashboard.question')),
            ],
        ),
        migrations.CreateModel(
            name='FlagCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_value', models.CharField(blank=True, max_length=100, null=True)),
                ('min_integer_value', models.IntegerField(blank=True, null=True)),
                ('is_inverted', models.IntegerField(default=False)),
                ('color', models.CharField(max_length=10)),
                ('flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='dashboard.summaryflag')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.question')),
            ],
        ),
        migrations.CreateModel(
            name='AdolescentResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('adolescent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.adolescent')),
                ('chosen_options', models.ManyToManyField(to='dashboard.option')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.question')),
            ],
        ),
    ]
