# Generated by Django 4.1.7 on 2023-09-22 23:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdolescentSummaryFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(db_index=True, max_length=50, unique=True)),
                ('computed_color_code', models.CharField(max_length=10)),
                ('updated_color_code', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FlagColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_code', models.CharField(max_length=10)),
                ('is_fallback', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FlagLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(db_index=True, max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='flagcondition',
            old_name='min_integer_value',
            new_name='expected_integer_value',
        ),
        migrations.RenameField(
            model_name='flagcondition',
            old_name='text_value',
            new_name='expected_value',
        ),
        migrations.RemoveField(
            model_name='flagcondition',
            name='color',
        ),
        migrations.RemoveField(
            model_name='flagcondition',
            name='flag',
        ),
        migrations.RemoveField(
            model_name='flagcondition',
            name='is_inverted',
        ),
        migrations.RemoveField(
            model_name='flagcondition',
            name='question',
        ),
        migrations.AddField(
            model_name='flagcondition',
            name='invert_operator_evaluation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flagcondition',
            name='is_required',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='flagcondition',
            name='operator',
            field=models.CharField(choices=[('equal_expected_value', 'equal_expected_value'), ('less_than_expected_integer_value', 'less_than_expected_integer_value'), ('q1_q2_difference_is_equal_to_expected_integer_value', 'q1_q2_difference_is_equal_to_expected_integer_value'), ('q1_q2_difference_is_less_than_expected_integer_value', 'q1_q2_difference_is_less_than_expected_integer_value'), ('age_is', 'age_is'), ('gender_is', 'gender_is')], default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flagcondition',
            name='priority',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='flagcondition',
            name='question1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='flag1s', to='dashboard.question'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flagcondition',
            name='question2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flag2s', to='dashboard.question'),
        ),
        migrations.AlterField(
            model_name='adolescent',
            name='other_names',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='adolescent',
            name='pid',
            field=models.CharField(db_index=True, default='', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adolescent',
            name='surname',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='adolescent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='adolescent',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='number',
            field=models.IntegerField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_id',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='section',
            name='question_type',
            field=models.CharField(choices=[('survey', 'survey'), ('assessment', 'assessment'), ('survey_feedback', 'survey_feedback')], db_index=True, default='survey', max_length=100),
        ),
        migrations.DeleteModel(
            name='SummaryFlag',
        ),
        migrations.AddField(
            model_name='flagcolor',
            name='flag_label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='dashboard.flaglabel'),
        ),
        migrations.AddField(
            model_name='adolescentsummaryflag',
            name='adolescent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.adolescent'),
        ),
        migrations.AddField(
            model_name='adolescentsummaryflag',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='flagcondition',
            name='flag_color',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='dashboard.flagcolor'),
            preserve_default=False,
        ),
    ]
