# Generated by Django 4.1.7 on 2023-09-10 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkuplocation',
            name='type',
            field=models.CharField(choices=[('primary', 'primary'), ('secondary', 'secondary'), ('community', 'community')], max_length=100),
        ),
    ]
