# Generated by Django 4.1.7 on 2023-09-15 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_adolescent_completed_question'),
        ('dashboard', '0002_alter_checkuplocation_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviousResponseRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_is', models.CharField(blank=True, max_length=100, null=True)),
                ('min_integer_value', models.IntegerField(blank=True, null=True)),
                ('is_inverted', models.IntegerField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionnaireSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('instruction', models.TextField()),
                ('order', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='SummaryFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admins_comment', models.TextField(blank=True, null=True)),
                ('question_type', models.TextField(choices=[('assessment', 'assessment'), ('survey', 'survey')])),
                ('question_id', models.CharField(max_length=50)),
                ('order', models.IntegerField(default=1)),
                ('text', models.CharField(max_length=200)),
                ('input_type', models.CharField(max_length=100)),
                ('answer_preamble', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('min_numeric_value', models.IntegerField(blank=True, null=True)),
                ('max_numeric_value', models.IntegerField(blank=True, null=True)),
                ('type_of_visit', models.CharField(blank=True, max_length=100, null=True)),
                ('min_age', models.IntegerField(blank=True, null=True)),
                ('max_age', models.IntegerField(blank=True, null=True)),
                ('gender', models.IntegerField(blank=True, null=True)),
                ('adolescent_type', models.CharField(blank=True, choices=[('primary', 'primary'), ('secondary', 'secondary'), ('community', 'community')], max_length=100, null=True)),
                ('invert_adolescent_attribute_requirements', models.BooleanField(blank=True, default=False, null=True)),
                ('previous_response_requirements', models.ManyToManyField(related_name='required_question', to='dashboard.previousresponserequirement')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='dashboard.questionnairesection')),
            ],
        ),
        migrations.AddField(
            model_name='previousresponserequirement',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.question'),
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('numeric_value', models.IntegerField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.question')),
            ],
        ),
        migrations.CreateModel(
            name='FlagCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_value', models.CharField(blank=True, max_length=100, null=True)),
                ('min_integer_value', models.IntegerField(blank=True, null=True)),
                ('is_inverted', models.IntegerField(default=False)),
                ('color', models.CharField(max_length=10)),
                ('flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='dashboard.summaryflag')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.question')),
            ],
        ),
        migrations.CreateModel(
            name='AdolescentResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simple_input', models.CharField(max_length=200)),
                ('adolescent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.adolescent')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.question')),
                ('response_options', models.ManyToManyField(to='dashboard.option')),
            ],
        ),
    ]
