# Generated by Django 4.1.7 on 2023-09-22 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_adolescentsummaryflag_flagcolor_flaglabel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flagcolor',
            name='color_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
