# Generated by Django 4.1.7 on 2023-09-15 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_previousresponserequirement_questionnairesection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='caption',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='input_type',
            field=models.CharField(choices=[('text_field', 'text_field'), ('number_field', 'number_field'), ('radio_button', 'radio_button'), ('checkboxes', 'checkboxes'), ('range_slider', 'range_slider')], max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='previous_response_requirements',
            field=models.ManyToManyField(blank=True, related_name='required_question', to='dashboard.previousresponserequirement'),
        ),
    ]
