# Generated by Django 4.1.7 on 2023-09-23 08:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0004_alter_flagcondition_operator'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdolescentSummaryFlag',
            new_name='SummaryFlag',
        ),
    ]
