# Generated by Django 4.1.7 on 2023-09-15 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_question_caption_alter_question_input_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='order',
            new_name='number',
        ),
        migrations.AlterField(
            model_name='question',
            name='caption',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.TextField(choices=[('survey', 'survey'), ('assessment', 'assessment')]),
        ),
    ]
