# Generated by Django 4.1.7 on 2023-09-23 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_flaglabel_label'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flaglabel',
            old_name='label',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='summaryflag',
            old_name='label',
            new_name='name',
        ),
    ]
