# Generated by Django 4.1.7 on 2023-09-23 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_rename_label_flaglabel_name_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='summaryflag',
            constraint=models.UniqueConstraint(fields=('adolescent', 'name'), name='Adolescen flag'),
        ),
    ]
