# Generated by Django 4.1.7 on 2023-09-23 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_summaryflag_adolescen flag'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='summaryflag',
            name='Adolescen flag',
        ),
        migrations.AddConstraint(
            model_name='summaryflag',
            constraint=models.UniqueConstraint(fields=('adolescent', 'name'), name='Adolescent flag'),
        ),
    ]
