# Generated by Django 4.1.7 on 2023-09-15 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_questionnairesection_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuestionnaireSection',
            new_name='Section',
        ),
    ]
