# Generated by Django 4.1.7 on 2023-09-15 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_rename_questionnairesection_section'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adolescentresponse',
            old_name='simple_input',
            new_name='text',
        ),
    ]
