# Generated by Django 4.1.7 on 2023-09-15 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_rename_simple_input_adolescentresponse_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adolescentresponse',
            old_name='response_options',
            new_name='chosen_options',
        ),
        migrations.AlterField(
            model_name='option',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='dashboard.question'),
        ),
    ]
