# Generated by Django 4.1.7 on 2023-09-24 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_summaryflag_updated_color_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='summaryflag',
            name='comment',
            field=models.CharField(default='This value was inffered.', max_length=200),
        ),
    ]
