# Generated by Django 4.1.7 on 2023-09-17 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_rename_response_options_adolescentresponse_chosen_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='question_type',
            field=models.CharField(choices=[('survey', 'survey'), ('assessment', 'assessment'), ('survey_feedback', 'survey_feedback')], default='survey', max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.TextField(choices=[('survey', 'survey'), ('assessment', 'assessment'), ('survey_feedback', 'survey_feedback')]),
        ),
    ]
