# Generated by Django 4.1.7 on 2023-09-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_alter_previousresponserequirement_is_inverted'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='requires_game',
            field=models.BooleanField(default=False),
        ),
    ]
