# Generated by Django 4.1.7 on 2023-09-17 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_section_requires_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
