# Generated by Django 4.2.3 on 2023-09-27 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0014_referral_service_treatment_referral_services"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="related_summary_flags",
            field=models.ManyToManyField(
                blank=True, null=True, to="dashboard.summaryflag"
            ),
        ),
    ]
