# Generated by Django 4.2.3 on 2023-10-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0015_service_related_summary_flags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="related_summary_flags",
        ),
        migrations.AddField(
            model_name="service",
            name="related_flag_label",
            field=models.ManyToManyField(
                blank=True, null=True, to="dashboard.flaglabel"
            ),
        ),
    ]
