# Generated by Django 4.1.7 on 2023-09-18 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_alter_question_question_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='previous_response_requirements',
        ),
        migrations.AddField(
            model_name='previousresponserequirement',
            name='requirement_for',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='previous_response_requirements', to='dashboard.question'),
            preserve_default=False,
        ),
    ]
