# Generated by Django 4.1.7 on 2023-10-01 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_remove_service_related_summary_flags_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='summaryflag',
            name='Adolescent flag',
        ),
        migrations.RemoveField(
            model_name='summaryflag',
            name='name',
        ),
        migrations.AlterField(
            model_name='flagcolor',
            name='color_code',
            field=models.CharField(choices=[('RED', '#ff0000'), ('ORANGE', '#ffa500'), ('GREEN', '#00ff00')], max_length=10),
        ),
        migrations.AlterField(
            model_name='flagcolor',
            name='color_name',
            field=models.CharField(blank=True, choices=[('RED', 'RED'), ('ORANGE', 'ORANGE'), ('GREEN', 'GREEN')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='summaryflag',
            name='computed_color_code',
            field=models.CharField(choices=[('RED', '#ff0000'), ('ORANGE', '#ffa500'), ('GREEN', '#00ff00')], max_length=10),
        ),
        migrations.AlterField(
            model_name='summaryflag',
            name='updated_color_code',
            field=models.CharField(blank=True, choices=[('RED', '#ff0000'), ('ORANGE', '#ffa500'), ('GREEN', '#00ff00')], max_length=10, null=True),
        ),
    ]
