# Generated by Django 4.1.7 on 2023-10-01 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_remove_summaryflag_adolescent flag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='summaryflag',
            name='label',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.flaglabel'),
        ),
        migrations.AddConstraint(
            model_name='summaryflag',
            constraint=models.UniqueConstraint(fields=('adolescent', 'label'), name='Adolescent flag'),
        ),
    ]
