# Generated by Django 4.1.7 on 2023-10-01 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_referral_status_alter_flagcolor_color_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('review', 'review'), ('completed', 'completed')], default='new', max_length=100),
        ),
        migrations.AlterField(
            model_name='service',
            name='related_flag_labels',
            field=models.ManyToManyField(blank=True, to='dashboard.flaglabel'),
        ),
        migrations.AlterField(
            model_name='summaryflag',
            name='label',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.flaglabel'),
            preserve_default=False,
        ),
    ]
