# Generated by Django 4.1.7 on 2023-10-09 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_alter_referral_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treatment',
            old_name='reamrks',
            new_name='remarks',
        ),
        migrations.AlterField(
            model_name='question',
            name='gender',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='date_of_service',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='is_referred',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='picture_confirmed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='referral',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='treatment', to='dashboard.referral'),
        ),
    ]
