# Generated by Django 4.1.7 on 2023-10-09 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_rename_reamrks_treatment_remarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='further_referral_facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.facility'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='no_referral_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='provided_treaments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
