# Generated by Django 4.1.7 on 2023-10-10 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_treatment_further_referral_facility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='apk_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
