# Generated by Django 4.1.7 on 2023-10-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_question_apk_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='context',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
