# Generated by Django 4.1.7 on 2023-10-15 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_option_context'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adolescentresponse',
            name='chosen_options',
            field=models.ManyToManyField(blank=True, to='dashboard.option'),
        ),
    ]
