# Generated by Django 4.1.7 on 2023-10-19 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_alter_adolescentresponse_chosen_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='flagcondition',
            name='max_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flagcondition',
            name='min_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flagcondition',
            name='range_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flagcondition',
            name='range_min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flagcondition',
            name='operator',
            field=models.CharField(choices=[('equal_expected_value', 'equal_expected_value'), ('less_than_expected_integer_value', 'less_than_expected_integer_value'), ('q1_q2_difference_is_equal_to_expected_integer_value', 'q1_q2_difference_is_equal_to_expected_integer_value'), ('q1_q2_difference_is_less_than_expected_integer_value', 'q1_q2_difference_is_less_than_expected_integer_value'), ('min_age', 'min_age'), ('range_sum_between', 'range_sum_between'), ('gender_is', 'gender_is')], max_length=100),
        ),
    ]
