# Generated by Django 4.1.7 on 2023-10-19 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_flagcondition_max_age_flagcondition_min_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='audios/'),
        ),
        migrations.AddField(
            model_name='question',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='audios/'),
        ),
    ]
