# Generated by Django 4.1.7 on 2023-11-17 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_option_audio_file_question_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='adolescent',
            name='grade',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='adolescent',
            name='residential_status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='adolescent',
            name='school',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='adolescent',
            name='type',
            field=models.CharField(choices=[('basic', 'basic'), ('secondary', 'secondary'), ('community', 'community')], max_length=20),
        ),
        migrations.AlterField(
            model_name='checkuplocation',
            name='type',
            field=models.CharField(choices=[('basic', 'basic'), ('secondary', 'secondary'), ('community', 'community')], max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.TextField(choices=[('survey', 'survey'), ('assessment', 'assessment'), ('survey_feedback', 'survey_feedback'), ('practice', 'practice')]),
        ),
        migrations.AlterField(
            model_name='section',
            name='question_type',
            field=models.CharField(choices=[('survey', 'survey'), ('assessment', 'assessment'), ('survey_feedback', 'survey_feedback'), ('practice', 'practice')], db_index=True, default='survey', max_length=100),
        ),
    ]
