# Generated by Django 4.1.7 on 2023-11-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_adolescent_leaves_in_catchment'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='to_be_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='adolescent',
            name='consent',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
