# Generated by Django 4.1.7 on 2023-11-26 14:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_flagcondition_name_alter_flagcolor_color_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adolescent',
            name='localnode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adolescent',
            name='synced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adolescentresponse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adolescentresponse',
            name='localnode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adolescentresponse',
            name='synced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adolescentresponse',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='adolescentresponse',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='checkuplocation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkuplocation',
            name='localnode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='checkuplocation',
            name='synced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checkuplocation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='localnode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='synced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='referral',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='treatment',
            name='localnode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='treatment',
            name='synced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='treatment',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
