# Generated by Django 4.1.7 on 2023-12-04 23:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0036_alter_adolescent_id_alter_adolescentresponse_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adolescent',
            name='id',
            field=models.CharField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='adolescentresponse',
            name='id',
            field=models.CharField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='checkuplocation',
            name='id',
            field=models.CharField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='referral',
            name='id',
            field=models.CharField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='id',
            field=models.CharField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
