# Generated by Django 4.1.7 on 2023-12-05 00:01

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0039_option_created_at_option_localnode_option_synced_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facility',
            name='localnode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='synced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='facility',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='flagcolor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flagcolor',
            name='localnode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='flagcolor',
            name='synced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flagcolor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='flagcolor',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='flagcondition',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flagcondition',
            name='localnode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='flagcondition',
            name='synced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flagcondition',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='flagcondition',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='flaglabel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flaglabel',
            name='localnode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='flaglabel',
            name='synced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flaglabel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='flaglabel',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='service',
            name='localnode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='synced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='summaryflag',
            name='localnode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='summaryflag',
            name='synced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='summaryflag',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='facility',
            name='id',
            field=models.CharField(db_index=True, default=uuid.uuid4, max_length=120, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='flagcolor',
            name='id',
            field=models.CharField(db_index=True, default=uuid.uuid4, max_length=120, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='flagcondition',
            name='id',
            field=models.CharField(db_index=True, default=uuid.uuid4, max_length=120, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='flaglabel',
            name='id',
            field=models.CharField(db_index=True, default=uuid.uuid4, max_length=120, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='service',
            name='id',
            field=models.CharField(db_index=True, default=uuid.uuid4, max_length=120, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='summaryflag',
            name='id',
            field=models.CharField(db_index=True, default=uuid.uuid4, max_length=120, primary_key=True, serialize=False),
        ),
    ]
