# Generated by Django 4.1.7 on 2023-12-06 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0042_alter_adolescent_uuid_alter_adolescentresponse_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='caption',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
