# Generated by Django 4.1.7 on 2023-12-09 14:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0045_remove_adolescent_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adolescent',
            name='id',
            field=models.CharField(db_index=True, default=uuid.uuid4, max_length=120, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='adolescentresponse',
            name='id',
            field=models.CharField(db_index=True, default=uuid.uuid4, max_length=120, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='checkuplocation',
            name='id',
            field=models.CharField(db_index=True, default=uuid.uuid4, max_length=120, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='id',
            field=models.CharField(db_index=True, default=uuid.uuid4, max_length=120, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='flagcolor',
            name='id',
            field=models.CharField(db_index=True, default=uuid.uuid4, max_length=120, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='flagcondition',
            name='id',
            field=models.CharField(db_index=True, default=uuid.uuid4, max_length=120, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='flaglabel',
            name='id',
            field=models.CharField(db_index=True, default=uuid.uuid4, max_length=120, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='option',
            name='id',
            field=models.CharField(db_index=True, default=uuid.uuid4, max_length=120, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='previousresponserequirement',
            name='id',
            field=models.CharField(db_index=True, default=uuid.uuid4, max_length=120, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.CharField(db_index=True, default=uuid.uuid4, max_length=120, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='referral',
            name='id',
            field=models.CharField(db_index=True, default=uuid.uuid4, max_length=120, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='id',
            field=models.CharField(db_index=True, default=uuid.uuid4, max_length=120, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='id',
            field=models.CharField(db_index=True, default=uuid.uuid4, max_length=120, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='summaryflag',
            name='id',
            field=models.CharField(db_index=True, default=uuid.uuid4, max_length=120, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='id',
            field=models.CharField(db_index=True, default=uuid.uuid4, max_length=120, primary_key=True, serialize=False, unique=True),
        ),
    ]
