# Generated by Django 4.1.7 on 2023-12-11 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0048_alter_adolescent_id_alter_adolescent_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adolescentresponse',
            name='text',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='adolescent_type',
            field=models.CharField(blank=True, choices=[('basic', 'basic'), ('secondary', 'secondary'), ('community', 'community')], max_length=100, null=True),
        ),
    ]
