# Generated by Django 4.1.6 on 2023-12-11 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0048_alter_adolescent_id_alter_adolescent_uuid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="adolescent_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("basic", "basic"),
                    ("secondary", "secondary"),
                    ("community", "community"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
