# Generated by Django 4.1.7 on 2023-12-11 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0049_alter_adolescentresponse_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adolescentresponse',
            name='text',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
