# Generated by Django 4.1.7 on 2023-12-30 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0049_alter_question_adolescent_type'),
        ('dashboard', '0052_alter_adolescentresponse_text'),
    ]

    operations = [
    ]
