# Generated by Django 4.1.7 on 2023-12-30 13:43

from django.db import migrations, models
import django.db.models.deletion
from uuid_extensions import uuid7


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0053_merge_20231230_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionGroup',
            fields=[
                ('id', models.CharField(db_index=True, default=uuid7, max_length=120, primary_key=True, serialize=False, unique=True)),
                ('uuid', models.UUIDField(default=uuid7, null=True)),
                ('localnode', models.CharField(blank=True, max_length=100, null=True)),
                ('synced', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('group_effect', models.CharField(choices=[('highest_value', 'highest_value'), ('lowest_value', 'lowest_value')], max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='question',
            name='dependent_on_flag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.summaryflag'),
        ),
        migrations.AddField(
            model_name='question',
            name='expected_flag_color',
            field=models.CharField(blank=True, choices=[('#808080', 'GREY'), ('#ff0000', 'RED'), ('#ffa500', 'ORANGE'), ('#00ff00', 'GREEN')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='max_group_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='min_group_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='dashboard.questiongroup'),
        ),
        migrations.AddField(
            model_name='question',
            name='previous_question_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dependent_questions', to='dashboard.questiongroup'),
        ),
    ]
