# Generated by Django 4.1.7 on 2023-12-31 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0055_flagcondition_question_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiongroup',
            name='util_function_tag',
            field=models.CharField(blank=True, choices=[('right_grip_test', 'right_grip_test'), ('left_grip_test', 'left_grip_test')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='flagcondition',
            name='operator',
            field=models.CharField(choices=[('equal_expected_value', 'equal_expected_value'), ('less_than_expected_integer_value', 'less_than_expected_integer_value'), ('q1_q2_difference_is_equal_to_expected_integer_value', 'q1_q2_difference_is_equal_to_expected_integer_value'), ('q1_q2_difference_is_less_than_expected_integer_value', 'q1_q2_difference_is_less_than_expected_integer_value'), ('min_age', 'min_age'), ('range_sum_between', 'range_sum_between'), ('gender_is', 'gender_is'), ('invoke_bmi_sd_function', 'invoke_bmi_sd_function'), ('group_value_between', 'group_value_between'), ('compute_right_grip_test', 'compute_right_grip_test'), ('compute_left_grip_test', 'compute_left_grip_test')], max_length=100),
        ),
    ]
