# Generated by Django 4.1.7 on 2023-12-31 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0056_questiongroup_util_function_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='dependent_on_flag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.flagcolor'),
        ),
    ]
