# Generated by Django 4.1.7 on 2024-01-06 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0058_remove_question_dependent_on_flag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adolescent',
            name='check_up_reason',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
