# Generated by Django 4.1.7 on 2024-01-06 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0059_adolescent_check_up_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previousresponserequirement',
            name='dependent_on_flag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.flaglabel'),
        ),
    ]
