# Generated by Django 4.1.7 on 2024-01-06 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0060_alter_previousresponserequirement_dependent_on_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previousresponserequirement',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.question'),
        ),
    ]
