# Generated by Django 4.1.7 on 2024-01-06 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0062_rename_type_of_visit_question_study_phase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adolescent',
            old_name='visit_type',
            new_name='study_phase',
        ),
    ]
