# Generated by Django 4.1.7 on 2024-01-07 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0063_rename_visit_type_adolescent_study_phase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adolescentresponse',
            name='text',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
