# Generated by Django 4.1.7 on 2024-02-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0064_alter_adolescentresponse_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='adolescent',
            name='lang_iso',
            field=models.CharField(blank=True, db_index=True, default='fat', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='option',
            name='audio_file_fat',
            field=models.FileField(blank=True, null=True, upload_to='audios/'),
        ),
        migrations.AddField(
            model_name='question',
            name='audio_file_fat',
            field=models.FileField(blank=True, null=True, upload_to='audios/'),
        ),
    ]
