# Generated by Django 4.1.6 on 2024-01-11 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("dashboard", "0064_alter_adolescentresponse_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="OnSpotTreatment",
            fields=[
                (
                    "id",
                    models.CharField(
                        db_index=True,
                        default=uuid.uuid4,
                        max_length=120,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, null=True),
                ),
                ("localnode", models.CharField(blank=True, max_length=100, null=True)),
                ("synced", models.BooleanField(default=False)),
                ("provided_treaments", models.TextField(blank=True, null=True)),
                (
                    "total_service_cost",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                ("date_of_service", models.DateField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "adolescent_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.adolescent",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
