# Generated by Django 4.1.7 on 2024-02-06 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0066_alter_flagcondition_expected_integer_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='show_response_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.question'),
        ),
    ]
