# Generated by Django 4.1.7 on 2024-02-16 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0067_question_show_response_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='flagcondition',
            name='adolescent_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='variable_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
