# Generated by Django 4.1.7 on 2024-02-18 01:49

from django.db import migrations, models
import django.db.models.deletion
import uuid_extensions.uuid7


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0068_flagcondition_adolescent_type_question_variable_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdolescentActivityTime',
            fields=[
                ('id', models.CharField(db_index=True, default=uuid_extensions.uuid7, max_length=120, primary_key=True, serialize=False, unique=True)),
                ('uuid', models.UUIDField(default=uuid_extensions.uuid7, null=True)),
                ('localnode', models.CharField(blank=True, max_length=100, null=True)),
                ('synced', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField()),
                ('activity_tag', models.CharField(max_length=100)),
                ('adolescent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.adolescent')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
