# Generated by Django 4.1.7 on 2024-02-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0069_adolescentactivitytime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adolescentactivitytime',
            name='activity_tag',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
