# Generated by Django 4.1.7 on 2024-02-22 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0070_alter_adolescentactivitytime_activity_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.TextField(choices=[('pre_screening', 'pre_screening'), ('practice', 'practice'), ('survey', 'survey'), ('survey_feedback', 'survey_feedback'), ('physical_assessment', 'physical_assessment'), ('lab_assessment', 'lab_assessment'), ('clinical_assessment', 'clinical_assessment'), ('counsellor_assessment', 'counsellor_assessment'), ('evaluation', 'evaluation'), ('exit_interview', 'exit_interview')]),
        ),
    ]
