# Generated by Django 4.1.7 on 2024-02-24 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0071_alter_question_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='question_type',
            field=models.CharField(choices=[('pre_screening', 'pre_screening'), ('practice', 'practice'), ('survey', 'survey'), ('survey_feedback', 'survey_feedback'), ('physical_assessment', 'physical_assessment'), ('lab_assessment', 'lab_assessment'), ('clinical_assessment', 'clinical_assessment'), ('counsellor_assessment', 'counsellor_assessment'), ('evaluation', 'evaluation'), ('exit_interview', 'exit_interview')], db_index=True, default='survey', max_length=100),
        ),
    ]
