# Generated by Django 4.1.7 on 2024-03-09 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0073_appconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adolescentresponse',
            name='adolescent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='dashboard.adolescent'),
        ),
    ]
