# Generated by Django 4.1.7 on 2024-03-09 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0075_alter_flagcondition_operator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flagcolor',
            name='priority',
            field=models.IntegerField(default=1),
        ),
    ]
