# Generated by Django 4.1.7 on 2024-03-10 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0077_alter_flagcondition_operator'),
    ]

    operations = [
        migrations.AddField(
            model_name='flagcondition',
            name='gender',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
