# Generated by Django 4.1.7 on 2024-03-10 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0079_alter_flagcondition_operator'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='regex_error_message',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='response_regex',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
