# Generated by Django 4.1.7 on 2024-03-17 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0080_question_regex_error_message_question_response_regex'),
    ]

    operations = [
        migrations.AddField(
            model_name='summaryflag',
            name='context',
            field=models.TextField(blank=True, null=True),
        ),
    ]
