# Generated by Django 4.1.7 on 2024-03-18 12:37

from django.db import migrations, models
import ycheck.utils.storage


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0082_adolescent_content_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adolescent',
            name='content_hash',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='adolescent',
            name='picture',
            field=models.ImageField(blank=True, null=True, storage=ycheck.utils.storage.OverwriteStorage(), upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='adolescentactivitytime',
            name='content_hash',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='adolescentresponse',
            name='content_hash',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='appconfiguration',
            name='content_hash',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='checkuplocation',
            name='content_hash',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='content_hash',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='flagcolor',
            name='content_hash',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='flagcondition',
            name='content_hash',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='flaglabel',
            name='content_hash',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='option',
            name='audio_file',
            field=models.FileField(blank=True, null=True, storage=ycheck.utils.storage.OverwriteStorage(), upload_to='audios/'),
        ),
        migrations.AlterField(
            model_name='option',
            name='audio_file_fat',
            field=models.FileField(blank=True, null=True, storage=ycheck.utils.storage.OverwriteStorage(), upload_to='audios/'),
        ),
        migrations.AlterField(
            model_name='option',
            name='content_hash',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='option',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=ycheck.utils.storage.OverwriteStorage(), upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='previousresponserequirement',
            name='content_hash',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='audio_file',
            field=models.FileField(blank=True, null=True, storage=ycheck.utils.storage.OverwriteStorage(), upload_to='audios/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='audio_file_fat',
            field=models.FileField(blank=True, null=True, storage=ycheck.utils.storage.OverwriteStorage(), upload_to='audios/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='content_hash',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=ycheck.utils.storage.OverwriteStorage(), upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='questiongroup',
            name='content_hash',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='referral',
            name='content_hash',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='content_hash',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='content_hash',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='summaryflag',
            name='content_hash',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='content_hash',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
