# Generated by Django 4.1.7 on 2024-03-20 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0085_alter_adolescent_content_hash_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='adolescentresponse',
            constraint=models.UniqueConstraint(fields=('adolescent', 'question'), name='Unique response per question'),
        ),
    ]
