# Generated by Django 4.1.7 on 2024-03-24 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0086_adolescentresponse_unique response per question'),
    ]

    operations = [
        migrations.AddField(
            model_name='adolescent',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
