# Generated by Django 4.1.7 on 2024-03-24 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0088_auto_20240324_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='summaryflag',
            name='final_color_code',
            field=models.CharField(blank=True, choices=[('#808080', 'GREY'), ('#3c4e77', 'DARK_BLUE'), ('#ff0000', 'RED'), ('#ffa500', 'ORANGE'), ('#00ff00', 'GREEN')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='flagcolor',
            name='color_code',
            field=models.CharField(choices=[('#808080', 'GREY'), ('#3c4e77', 'DARK_BLUE'), ('#ff0000', 'RED'), ('#ffa500', 'ORANGE'), ('#00ff00', 'GREEN')], max_length=10),
        ),
        migrations.AlterField(
            model_name='previousresponserequirement',
            name='expected_flag_color',
            field=models.CharField(blank=True, choices=[('#808080', 'GREY'), ('#3c4e77', 'DARK_BLUE'), ('#ff0000', 'RED'), ('#ffa500', 'ORANGE'), ('#00ff00', 'GREEN')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='summaryflag',
            name='computed_color_code',
            field=models.CharField(choices=[('#808080', 'GREY'), ('#3c4e77', 'DARK_BLUE'), ('#ff0000', 'RED'), ('#ffa500', 'ORANGE'), ('#00ff00', 'GREEN')], max_length=10),
        ),
        migrations.AlterField(
            model_name='summaryflag',
            name='updated_color_code',
            field=models.CharField(blank=True, choices=[('#808080', 'GREY'), ('#3c4e77', 'DARK_BLUE'), ('#ff0000', 'RED'), ('#ffa500', 'ORANGE'), ('#00ff00', 'GREEN')], max_length=10, null=True),
        ),
    ]
