# Generated by Django 4.1.7 on 2024-04-04 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0089_summaryflag_final_color_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='total_service_cost_nhis',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adolescentresponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='dashboard.question'),
        ),
    ]
