# Generated by Django 4.2.10 on 2024-04-03 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0089_summaryflag_final_color_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="treatment",
            name="nhis_cost",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="adolescentresponse",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="responses",
                to="dashboard.question",
            ),
        ),
    ]
