# Generated by Django 4.1.7 on 2024-04-09 03:30

import dashboard.models.mixin
from django.db import migrations, models
import django.db.models.deletion
import uuid_extensions.uuid7


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0090_treatment_total_service_cost_nhis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='total_service_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='total_service_cost_nhis',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='ConditionTreatment',
            fields=[
                ('id', models.CharField(db_index=True, default=uuid_extensions.uuid7, max_length=120, primary_key=True, serialize=False, unique=True)),
                ('uuid', models.UUIDField(default=uuid_extensions.uuid7, null=True)),
                ('localnode', models.CharField(blank=True, max_length=100, null=True)),
                ('synced', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_hash', models.CharField(blank=True, max_length=128, null=True)),
                ('status', models.CharField(choices=[('full', 'full'), ('partial', 'partial'), ('none', 'none')], default='full', max_length=50)),
                ('total_service_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_service_cost_nhis', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comment', models.TextField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.service')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.treatment')),
            ],
            bases=(dashboard.models.mixin.UpstreamSyncMethodsModel, models.Model),
        ),
        migrations.AddConstraint(
            model_name='conditiontreatment',
            constraint=models.UniqueConstraint(fields=('treatment', 'service'), name='Condition treatment uniqueness'),
        ),
    ]
