# Generated by Django 4.1.7 on 2024-04-09 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0091_alter_treatment_total_service_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='is_onsite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='conditiontreatment',
            name='treatment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condition_treatements', to='dashboard.treatment'),
        ),
    ]
