# Generated by Django 5.0.4 on 2024-04-18 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0094_alter_conditiontreatment_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summaryflag',
            name='comment',
            field=models.CharField(default='This value was inferred/computed.', max_length=200),
        ),
    ]
