# Generated by Django 5.0.4 on 2024-06-11 20:39

import dashboard.models.mixin
import uuid_extensions.uuid7
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0096_adolescent_process_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputedAverageActivityTime',
            fields=[
                ('id', models.CharField(db_index=True, default=uuid_extensions.uuid7, max_length=120, primary_key=True, serialize=False, unique=True)),
                ('uuid', models.UUIDField(default=uuid_extensions.uuid7, null=True)),
                ('localnode', models.CharField(blank=True, max_length=100, null=True)),
                ('synced', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_hash', models.CharField(blank=True, max_length=128, null=True)),
                ('activity', models.CharField(db_index=True, max_length=100)),
                ('key', models.CharField(db_index=True, max_length=100, unique=True)),
                ('status', models.CharField(default='completed', max_length=50)),
                ('average_time_in_seconds', models.IntegerField(default=0)),
                ('order', models.IntegerField(default=0)),
                ('required', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=(dashboard.models.mixin.UpstreamSyncMethodsModel, models.Model),
        ),
    ]
