<<<<<<< HEAD
# Generated by Django 5.0.4 on 2024-07-03 21:39
=======
# Generated by Django 4.2.10 on 2024-07-03 18:18
>>>>>>> 4d2b0d3c2434e2e005b5f54ed24a94f56a157d29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('dashboard', '0097_computedaverageactivitytime'),
=======
        ("dashboard", "0097_computedaverageactivitytime"),
>>>>>>> 4d2b0d3c2434e2e005b5f54ed24a94f56a157d29
    ]

    operations = [
        migrations.AlterField(
<<<<<<< HEAD
            model_name='referral',
            name='service_type',
=======
            model_name="referral",
            name="service_type",
>>>>>>> 4d2b0d3c2434e2e005b5f54ed24a94f56a157d29
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
