# Generated by Django 5.0.4 on 2024-07-03 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0097_computedaverageactivitytime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='service_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
