# Generated by Django 4.2.10 on 2024-07-03 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0098_alter_referral_service_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="treatment",
            name="reason_for_referral",
            field=models.TextField(blank=True, null=True),
        ),
    ]
