# Generated by Django 5.0.4 on 2024-08-10 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0098_alter_referral_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='computedaverageactivitytime',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='computedaverageactivitytime',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
