# Generated by Django 5.0.4 on 2024-08-17 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0100_remove_adolescentresponse_unique_response_per_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='study_phase',
            field=models.CharField(blank=True, choices=[('pilot', 'pilot'), ('implementation', 'implementation'), ('followup', 'followup')], max_length=50, null=True),
        ),
    ]
