# Generated by Django 5.0.8 on 2024-08-18 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0104_flaglabel_exclude_if_not_flagged_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facility',
            options={'verbose_name_plural': 'facilities'},
        ),
        migrations.AlterField(
            model_name='question',
            name='exclude_if_not_flagged',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
