# Generated by Django 5.1 on 2024-08-30 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0106_question_related_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='related_label',
        ),
        migrations.AddField(
            model_name='question',
            name='related_labels',
            field=models.ManyToManyField(blank=True, null=True, related_name='questions', to='dashboard.flaglabel'),
        ),
    ]
