# Generated by Django 5.1 on 2024-09-06 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0108_alter_adolescentactivitytime_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='related_labels',
            field=models.ManyToManyField(blank=True, related_name='questions', to='dashboard.flaglabel'),
        ),
    ]
