# Generated by Django 5.1 on 2025-01-25 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0109_alter_question_related_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='adolescent',
            name='followup_completed',
            field=models.BooleanField(default=False),
        ),
    ]
