# Generated by Django 4.1.7 on 2023-09-09 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SetupPerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('manage_setup', 'Can manage setup'), ('manage_users', 'Can manage users'), ('view_main_dashboard', 'Can view main dashboard'), ('view_dashboard', 'Can view dashboard'), ('view_system_configuration', 'Can view system configuration'), ('manage_tasks', 'Can manage tasks'), ('manage_other_report', 'Can manage other reports'), ('manage_roles', 'Can manage roles'), ('view_user', 'Can view user'), ('add_user', 'Can add user'), ('edit_user', 'Can edit user'), ('delete_user', 'Can delete user'), ('add_patient', 'Can add new patient records'), ('view_patient', 'Can view patient records'), ('edit_patient', 'Can edit existing patient records'), ('delete_patient', 'Can delete patient records'), ('schedule_appointment', 'Can schedule new appointments'), ('view_appointment', 'Can view appointments'), ('reschedule_appointment', 'Can reschedule appointments'), ('cancel_appointment', 'Can cancel appointments'), ('add_medical_record', 'Can add new medical records'), ('view_medical_record', 'Can view medical records'), ('edit_medical_record', 'Can edit medical records'), ('delete_medical_record', 'Can delete medical records'), ('recommend_adolescent', 'Can recommend adolescent'), ('view_reports', 'Can view various system reports'), ('generate_reports', 'Can generate specific reports'), ('access_system_config', 'Can access system configurations'), ('edit_system_config', 'Can edit and update system configurations')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
