# Generated by Django 4.1.7 on 2023-12-06 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0007_nodeconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodeconfig',
            name='users_sync_status_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nodeconfig',
            name='adolescents_sync_status',
            field=models.CharField(choices=[('idle', 'idle'), ('progress', 'progress'), ('completed', 'completed')], max_length=200),
        ),
        migrations.AlterField(
            model_name='nodeconfig',
            name='referrals_sync_status',
            field=models.CharField(choices=[('idle', 'idle'), ('progress', 'progress'), ('completed', 'completed')], max_length=200),
        ),
        migrations.AlterField(
            model_name='nodeconfig',
            name='treatments_sync_status',
            field=models.CharField(choices=[('idle', 'idle'), ('progress', 'progress'), ('completed', 'completed')], max_length=200),
        ),
    ]
