# Generated by Django 4.1.7 on 2023-12-06 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0008_nodeconfig_users_sync_status_message_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nodeconfig',
            old_name='adolescents_sync_status',
            new_name='adolescents_upload_status',
        ),
        migrations.RenameField(
            model_name='nodeconfig',
            old_name='users_sync_status',
            new_name='questions_download_status',
        ),
        migrations.RenameField(
            model_name='nodeconfig',
            old_name='users_sync_status_message',
            new_name='questions_download_status_message',
        ),
        migrations.RenameField(
            model_name='nodeconfig',
            old_name='referrals_sync_status',
            new_name='referrals_upload_status',
        ),
        migrations.RenameField(
            model_name='nodeconfig',
            old_name='treatments_sync_status',
            new_name='treatments_upload_status',
        ),
        migrations.AddField(
            model_name='nodeconfig',
            name='users_download_status',
            field=models.CharField(choices=[('idle', 'idle'), ('progress', 'progress'), ('completed', 'completed')], default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nodeconfig',
            name='users_download_status_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
