# Generated by Django 4.1.7 on 2023-12-07 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0009_rename_adolescents_sync_status_nodeconfig_adolescents_upload_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodeconfig',
            name='adolescents_upload_status_message',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
