# Generated by Django 4.2.10 on 2024-04-24 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("setup", "0015_alter_nodeconfig_up_stream_host"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="setupperm",
            options={
                "default_permissions": (),
                "managed": False,
                "permissions": [
                    ("manage_setup", "Can manage setup"),
                    ("manage_users", "Can manage users"),
                    ("view_dashboard", "Can view dashboard"),
                    ("view_system_configuration", "Can view system configuration"),
                    ("access_all_referrals", "Can access all referrals"),
                    ("access_referrals", "Can access referrals menu"),
                    ("access_all_patients", "Can access all patients"),
                    ("access_all_treatments", "Can access all treatment records"),
                    ("access_treatments", "Can access treatments menu"),
                    ("access_reports", "Can generate/access reports menu"),
                    ("view_user", "Can view user"),
                    ("add_user", "Can add user"),
                    ("edit_user", "Can edit user"),
                    ("delete_user", "Can delete user"),
                    ("add_patient", "Can add new patient records"),
                    ("view_patient", "Can view patient records"),
                    ("edit_patient", "Can edit existing patient records"),
                    ("delete_patient", "Can delete patient records"),
                    ("manage_service", "Can manage services"),
                    ("manage_facility", "Can manage facility"),
                    ("edit_system_config", "Can edit and update system configurations"),
                    ("change_referral", "Can change referral"),
                ],
            },
        ),
    ]
