from dashboard.models.adolescent import *
from dashboard.models.flags import *
from dashboard.models.facility import *
from dashboard.models.treatment import *
from dashboard.models.referrals import *
from dashboard.models.service import *
from dashboard.models.section import *
from dashboard.models.questions import *
from dashboard.models.checkup_location import *
from dashboard.models.previous_question_requirement import *
from dashboard.models.app_configuration import *
from dashboard.models.sync_deletion_models import *
