export const ADD_ADOLESCENT_REQUEST = 'ADD_ADOLESCENT_REQUEST'
export const ADD_ADOLESCENT_SUCCESS = 'ADD_ADOLESCENT_SUCCESS'
export const ADD_ADOLESCENT_FAILED = 'ADD_ADOLESCENT_FAILED'


export const BASIC_SCHOOL_LIST_REQUEST = 'BASIC_SCHOOL_LIST_REQUEST'
export const BASIC_SCHOOL_LIST_SUCCESS = 'BASIC_SCHOOL_LIST_SUCCESS'
export const BASIC_SCHOOL_LIST_FAILED = 'BASIC_SCHOOL_LIST_FAILED'
