export const ADD_ADOLESCENT_REQUEST = 'ADD_ADOLESCENT_REQUEST'
export const ADD_ADOLESCENT_SUCCESS = 'ADD_ADOLESCENT_SUCCESS'
export const ADD_ADOLESCENT_FAILED = 'ADD_ADOLESCENT_FAILED'
export const RESET_ADOLESCENT_INFO = 'RESET_ADOLESCENT_INFO';


export const  ADOLESCENT_LIST_REQUEST = ' ADOLESCENT_LIST_REQUEST'
export const  ADOLESCENT_LIST_SUCCESS = ' ADOLESCENT_LIST_SUCCESS'
export const  ADOLESCENT_LIST_FAILED = ' ADOLESCENT_LIST_FAILED'

export const  ADOLESCENT_DELETE_REQUEST = ' ADOLESCENT_DELETE_REQUEST'
export const  ADOLESCENT_DELETE_SUCCESS = ' ADOLESCENT_DELETE_SUCCESS'
export const  ADOLESCENT_DELETE_FAILED = ' ADOLESCENT_DELETE_FAILED'

export const ADOLESCENT_REQUEST = 'ADOLESCENT_REQUEST'
export const ADOLESCENT_SUCCESS = 'ADOLESCENT_SUCCESS'
export const ADOLESCENT_FAILED = 'ADOLESCENT_FAILED'

export const ADOLESCENT_SERACH_REQUEST = 'ADOLESCENT_SERACH_REQUEST'
export const ADOLESCENT_SERACH_SUCCESS = 'ADOLESCENT_SERACH_SUCCESS'
export const ADOLESCENT_SERACH_FAILED = 'ADOLESCENT_SERACH_FAILED'


export const  GET_ALL_ADOLESCENT_REQUEST = ' GET_ALL_ADOLESCENT_REQUEST'
export const  GET_ALL_ADOLESCENT_SUCCESS = ' GET_ALL_ADOLESCENT_SUCCESS'
export const  GET_ALL_ADOLESCENT_FAILED = ' GET_ALL_ADOLESCENT_FAILED'

export const  GET_ALL_ADOLESCENT_TYPE_REQUEST = ' GET_ALL_ADOLESCENT_TYPE_REQUEST'
export const  GET_ALL_ADOLESCENT_TYPE_SUCCESS = ' GET_ALL_ADOLESCENT_TYPE_SUCCESS'
export const  GET_ALL_ADOLESCENT_TYPE_FAILED = ' GET_ALL_ADOLESCENT_TYPE_FAILED'