
export const  ADD_OPTIONS_REQUEST = ' ADD_OPTIONS_REQUEST'
export const  ADD_OPTIONS_SUCCESS = ' ADD_OPTIONS_SUCCESS'
export const  ADD_OPTIONS_FAILED = ' ADD_OPTIONS_FAILED'

export const  GET_QUESTION_OPTIONS_REQUEST = ' GET_QUESTION_OPTIONS_REQUEST'
export const  GET_QUESTION_OPTIONS_SUCCESS = ' GET_QUESTION_OPTIONS_SUCCESS'
export const  GET_QUESTION_OPTIONS_FAILED = ' GET_QUESTION_OPTIONS_FAILED'
