export const ADD_ADOLESCENT_RESPONSE_REQUEST = 'ADD_ADOLESCENT_RESPONSE_REQUEST'
export const ADD_ADOLESCENT_RESPONSE_SUCCESS = 'ADD_ADOLESCENT_RESPONSE_SUCCESS'
export const ADD_ADOLESCENT_RESPONSE_FAILED = 'ADD_ADOLESCENT_RESPONSE_FAILED'


export const  ADOLESCENT_LIST_REQUEST = ' ADOLESCENT_LIST_REQUEST'
export const  ADOLESCENT_LIST_SUCCESS = ' ADOLESCENT_LIST_SUCCESS'
export const  ADOLESCENT_LIST_FAILED = ' ADOLESCENT_LIST_FAILED'