export const  HOME_QUESTIONS_REQUEST = ' HOME_QUESTIONS_REQUEST'
export const  HOME_QUESTIONS_SUCCESS = ' HOME_QUESTIONS_SUCCESS'
export const  HOME_QUESTIONS_FAILED = ' HOME_QUESTIONS_FAILED'

export const  ADD_HOME_QUESTIONS_REQUEST = ' ADD_HOME_QUESTIONS_REQUEST'
export const  ADD_HOME_QUESTIONS_SUCCESS = ' ADD_HOME_QUESTIONS_SUCCESS'
export const  ADD_HOME_QUESTIONS_FAILED = ' ADD_HOME_QUESTIONS_FAILED'
