
export const  PERMISSION_LIST_REQUEST = ' PERMISSION_LIST_REQUEST'
export const  PERMISSION_LIST_SUCCESS = ' PERMISSION_LIST_SUCCESS'
export const  PERMISSION_LIST_FAILED = ' PERMISSION_LIST_FAILED'

export const  GET_USERS_FOR_PERMISSION_LIST_REQUEST = ' GET_USERS_FOR_PERMISSION_LIST_REQUEST'
export const  GET_USERS_FOR_PERMISSION_LIST_SUCCESS = ' GET_USERS_FOR_PERMISSION_LIST_SUCCESS'
export const  GET_USERS_FOR_PERMISSION_LIST_FAILED = ' GET_USERS_FOR_PERMISSION_LIST_FAILED'

export const  ASSIGN_PERMISSION_REQUEST = ' ASSIGN_PERMISSION_REQUEST'
export const  ASSIGN_PERMISSION_SUCCESS = ' ASSIGN_PERMISSION_SUCCESS'
export const  ASSIGN_PERMISSION_FAILED = ' ASSIGN_PERMISSION_FAILED'
