
export const  PERMISSION_LIST_REQUEST = ' PERMISSION_LIST_REQUEST'
export const  PERMISSION_LIST_SUCCESS = ' PERMISSION_LIST_SUCCESS'
export const  PERMISSION_LIST_FAILED = ' PERMISSION_LIST_FAILED'

export const  GET_USERS_FOR_PERMISSION_LIST_REQUEST = ' GET_USERS_FOR_PERMISSION_LIST_REQUEST'
export const  GET_USERS_FOR_PERMISSION_LIST_SUCCESS = ' GET_USERS_FOR_PERMISSION_LIST_SUCCESS'
export const  GET_USERS_FOR_PERMISSION_LIST_FAILED = ' GET_USERS_FOR_PERMISSION_LIST_FAILED'

export const  ASSIGN_PERMISSION_REQUEST = ' ASSIGN_PERMISSION_REQUEST'
export const  ASSIGN_PERMISSION_SUCCESS = ' ASSIGN_PERMISSION_SUCCESS'
export const  ASSIGN_PERMISSION_FAILED = ' ASSIGN_PERMISSION_FAILED'

export const  GET_USER_PERMISSION_REQUEST = ' GET_USER_PERMISSION_REQUEST'
export const  GET_USER_PERMISSION_SUCCESS = ' GET_USER_PERMISSION_SUCCESS'
export const  GET_USER_PERMISSION_FAILED = ' GET_USER_PERMISSION_FAILED'

export const  REVOKE_PERMISSION_REQUEST = ' REVOKE_PERMISSION_REQUEST'
export const  REVOKE_PERMISSION_SUCCESS = ' REVOKE_PERMISSION_SUCCESS'
export const  REVOKE_PERMISSION_FAILED = ' REVOKE_PERMISSION_FAILED'