export const BASIC_SCHOOL_REQUEST = 'BASIC_SCHOOL_REQUEST'
export const BASIC_SCHOOL_SUCCESS = 'BASIC_SCHOOL_SUCCESS'
export const BASIC_SCHOOL_FAILED = 'BASIC_SCHOOL_FAILED'

export const BASIC_SCHOOL_DELETE_REQUEST = 'BASIC_SCHOOL_DELETE_REQUEST'
export const BASIC_SCHOOL_DELETE_SUCCESS = 'BASIC_SCHOOL_DELETE_SUCCESS'
export const BASIC_SCHOOL_DELETE_FAILED = 'BASIC_SCHOOL_DELETE_FAILED'

export const BASIC_SCHOOL_LIST_REQUEST = 'BASIC_SCHOOL_LIST_REQUEST'
export const BASIC_SCHOOL_LIST_SUCCESS = 'BASIC_SCHOOL_LIST_SUCCESS'
export const BASIC_SCHOOL_LIST_FAILED = 'BASIC_SCHOOL_LIST_FAILED'

export const COMMUNITY_REQUEST = 'COMMUNITY_REQUEST'
export const COMMUNITY_SUCCESS = 'COMMUNITY_SUCCESS'
export const COMMUNITY_FAILED = 'COMMUNITY_FAILED'

export const SHS_SCHOOL_REQUEST = 'SHS_SCHOOL_REQUEST'
export const SHS_SCHOOL_SUCCESS = 'SHS_SCHOOL_SUCCESS'
export const SHS_SCHOOL_FAILED = 'SHS_SCHOOL_FAILED'