export const SECURITY_QUESTION_REQUEST = 'SECURITY_QUESTION_REQUEST'
export const SECURITY_QUESTION_SUCCESS = 'SECURITY_QUESTION_SUCCESS'
export const SECURITY_QUESTION_FAILED = 'SECURITY_QUESTION_FAILED'