export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED'


export const USER_REGISTRATION_REQUEST = 'USER_REGISTRATION_REQUEST'
export const USER_REGISTRATION_SUCCESS = 'USER_REGISTRATION_SUCCESS'
export const USER_REGISTRATION_FAILED = 'USER_REGISTRATION_FAILED'


export const GET_ALL_USERS_REQUEST = 'GET_ALL_USERS_REQUEST'
export const GET_ALL_USERS_SUCCESS = 'GET_ALL_USERS_SUCCESS'
export const GET_ALL_USERS_FAILED = 'GET_ALL_USERS_FAILED'

export const GET_TOTAL_USERS_REQUEST = 'GET_TOTAL_USERS_REQUEST'
export const GET_TOTAL_USERS_SUCCESS = 'GET_TOTAL_USERS_SUCCESS'
export const GET_TOTAL_USERS_FAILED = 'GET_TOTAL_USERS_FAILED'


export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST'
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS'
export const DELETE_USER_FAILED = 'DELETE_USER_FAILED'

export const USER_SERACH_REQUEST = 'USER_SERACH_REQUEST'
export const USER_SERACH_SUCCESS = 'USER_SERACH_SUCCESS'
export const USER_SERACH_FAILED = 'USER_SERACH_FAILED'
//
export const USER_LOGOUT = 'USER_LOGOUT'
export const RESET_USER_SEARCH = 'USER_LOGOUT'